### ISSUE TITLE
Question: Why use ts-node instead of built it first and 'run in node.js'

### ISSUE THREAD

**Issue by Garfield550** [AOSC-Dev/ananbot#30]
```shell
# Execute a script as `node` + `tsc`. 
ts-node script.ts
```

ts-node just using tsc build code to javascript and run it in node.js, so I can't understand why you do that, why not build code first?

OR...

Why you execute ts-node using npx?

Your packages.json already contain `ts-node` as dependence, just use `yarn run` or `npm run` is enough.

**Comment by eatradish** [comment]
Yes, this is a problem
What do you think of this? E.g:
```
  "scripts": {
    "start": "node dist/src/index.js"
    "build": "tsc"
```

**Comment by eatradish** [comment]
Done.

See https://github.com/AOSC-Dev/ananbot/commit/b02ac98dc3f0deb9b53593c180bfd504ce5801a4 and 582f9683b8c984b1496e005c738ea41eff9c0400
(I forgot to delete the contents of scripts when I used the package.json of other projects. I am sorry here.)

**Comment by Garfield550** [comment]
> Yes, this is a problem
> What do you think of this? E.g:
> 
> ```
>   "scripts": {
>     "start": "node dist/src/index.js"
>     "build": "tsc"
> ```

I saw you removed `ts-node`, well, it is okay... but how do you start a development environment?

**Comment by eatradish** [comment]
> > Yes, this is a problem
> > What do you think of this? E.g:
> > ```
> >   "scripts": {
> >     "start": "node dist/src/index.js"
> >     "build": "tsc"
> > ```
> 
> I saw you removed `ts-node`, well, it is okay... but how do you start a development environment?

Should we do this?

```
  "scripts": {
    "start": "node dist/src/index.js",
    "build": "tsc",
    "test": "ts-node-dev --respawn --transpileOnly index.ts"
   }
```
and add `ts-node` to `devDependencies` ?

**Comment by Garfield550** [comment]
> > > Yes, this is a problem
> > > What do you think of this? E.g:
> > > ```
> > >   "scripts": {
> > >     "start": "node dist/src/index.js"
> > >     "build": "tsc"
> > > ```
> > 
> > 
> > I saw you removed `ts-node`, well, it is okay... but how do you start a development environment?
> 
> Should we do this?
> 
> ```
>   "scripts": {
>     "start": "node dist/src/index.js",
>     "build": "tsc",
>     "test": "ts-node-dev --respawn --transpileOnly index.ts"
>    }
> ```
> 
> and add `ts-node` to `devDependencies` ?

```json
"scripts": {
  "start": "node dist/src/index.js",
  "build": "tsc",
  "dev": "ts-node-dev --respawn --transpileOnly index.ts"
}
```

**Comment by eatradish** [comment]
> > > > Yes, this is a problem
> > > > What do you think of this? E.g:
> > > > ```
> > > >   "scripts": {
> > > >     "start": "node dist/src/index.js"
> > > >     "build": "tsc"
> > > > ```
> > > 
> > > 
> > > I saw you removed `ts-node`, well, it is okay... but how do you start a development environment?
> > 
> > 
> > Should we do this?
> > ```
> >   "scripts": {
> >     "start": "node dist/src/index.js",
> >     "build": "tsc",
> >     "test": "ts-node-dev --respawn --transpileOnly index.ts"
> >    }
> > ```
> > 
> > 
> > and add `ts-node` to `devDependencies` ?
> 
> ```json
> "scripts": {
>   "start": "node dist/src/index.js",
>   "build": "tsc",
>   "dev": "ts-node-dev --respawn --transpileOnly index.ts"
> }
> ```

Done. See  9216b5b926d7d943305354eb59fed2f69fb7bbcf
